var namespacees_1_1manueldonoso_1_1academia_1_1controller =
[
    [ "Cambio_ContrasenaController", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_cambio___contrasena_controller.html", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_cambio___contrasena_controller" ],
    [ "Contrato_registroController", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_contrato__registro_controller.html", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_contrato__registro_controller" ],
    [ "DashBoard_AdministradorController", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_dash_board___administrador_controller.html", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_dash_board___administrador_controller" ],
    [ "DashBoard_AlumnoController", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_dash_board___alumno_controller.html", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_dash_board___alumno_controller" ],
    [ "DashBoard_ProfesorController", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_dash_board___profesor_controller.html", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_dash_board___profesor_controller" ],
    [ "Escritorio_DefectoController", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_escritorio___defecto_controller.html", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_escritorio___defecto_controller" ],
    [ "LoginController", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_login_controller.html", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_login_controller" ],
    [ "MisDatosController", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_mis_datos_controller.html", "classes_1_1manueldonoso_1_1academia_1_1controller_1_1_mis_datos_controller" ]
];